// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Agent struct {
	ID        pgtype.UUID
	Name      pgtype.Text
	Endpoint  pgtype.Text
	Type      pgtype.Text
	Active    pgtype.Bool
	DeletedAt pgtype.Timestamptz
}

type AgentRun struct {
	ID               pgtype.UUID
	ExecutionStateID pgtype.UUID
	AgentID          pgtype.UUID
	Status           pgtype.Text
	Input            []byte
	Output           []byte
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type Approval struct {
	ID               pgtype.UUID
	ExecutionStateID pgtype.UUID
	Status           pgtype.Text
	Reviewer         pgtype.Text
	Comment          pgtype.Text
	ApprovedAt       pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type Artifact struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Type          pgtype.Text
	Name          pgtype.Text
	LatestVersion pgtype.Int4
	CreatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type ArtifactVersion struct {
	ID         pgtype.UUID
	ArtifactID pgtype.UUID
	Version    pgtype.Int4
	StorageUri pgtype.Text
	Checksum   pgtype.Text
	Metadata   []byte
	CreatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type AuditLog struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	Actor     pgtype.Text
	Action    pgtype.Text
	Payload   []byte
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type MemoryChunk struct {
	ID                pgtype.UUID
	ArtifactVersionID pgtype.UUID
	ChunkIndex        pgtype.Int4
	Content           pgtype.Text
	Embedding         pgvector.Vector
	Metadata          []byte
	DeletedAt         pgtype.Timestamptz
}

type Project struct {
	ID              pgtype.UUID
	Name            string
	Description     pgtype.Text
	WorkflowID      pgtype.UUID
	WorkflowVersion pgtype.Int4
	Status          pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type Workflow struct {
	ID         pgtype.UUID
	Name       string
	Version    pgtype.Int4
	StartState pgtype.Text
	Active     pgtype.Bool
	CreatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type WorkflowEvent struct {
	ID          pgtype.UUID
	ExecutionID pgtype.UUID
	EventName   pgtype.Text
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type WorkflowExecution struct {
	ID           pgtype.UUID
	ProjectID    pgtype.UUID
	WorkflowID   pgtype.UUID
	CurrentState pgtype.Text
	Status       pgtype.Text
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type WorkflowExecutionState struct {
	ID          pgtype.UUID
	ExecutionID pgtype.UUID
	StateKey    pgtype.Text
	Status      pgtype.Text
	EnteredAt   pgtype.Timestamptz
	ExitedAt    pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type WorkflowState struct {
	ID             pgtype.UUID
	WorkflowID     pgtype.UUID
	StateKey       pgtype.Text
	StateName      pgtype.Text
	AgentName      pgtype.Text
	TimeoutSeconds pgtype.Int4
	RetryLimit     pgtype.Int4
	IsTerminal     pgtype.Bool
	DeletedAt      pgtype.Timestamptz
}

type WorkflowStateInput struct {
	ID              pgtype.UUID
	WorkflowStateID pgtype.UUID
	ArtifactType    string
	Required        pgtype.Bool
	DeletedAt       pgtype.Timestamptz
}

type WorkflowStateOutput struct {
	ID              pgtype.UUID
	WorkflowStateID pgtype.UUID
	ArtifactType    string
	DeletedAt       pgtype.Timestamptz
}

type WorkflowTransition struct {
	ID         pgtype.UUID
	WorkflowID pgtype.UUID
	FromState  pgtype.Text
	EventName  pgtype.Text
	Condition  pgtype.Text
	ToState    pgtype.Text
	DeletedAt  pgtype.Timestamptz
}
