// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createAgent = `-- name: CreateAgent :one

INSERT INTO agent (
    id, name, endpoint, type, active, deleted_at
)
VALUES ($1,$2,$3,$4,$5,NULL)
RETURNING id, name, endpoint, type, active, deleted_at
`

type CreateAgentParams struct {
	ID       pgtype.UUID
	Name     pgtype.Text
	Endpoint pgtype.Text
	Type     pgtype.Text
	Active   pgtype.Bool
}

// =========================
// AGENT
// =========================
func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.ID,
		arg.Name,
		arg.Endpoint,
		arg.Type,
		arg.Active,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Type,
		&i.Active,
		&i.DeletedAt,
	)
	return i, err
}

const createAgentRun = `-- name: CreateAgentRun :one

INSERT INTO agent_run (
    id, execution_state_id, agent_id, status, input, output,
    started_at, finished_at, deleted_at
)
VALUES ($1,$2,$3,$4,$5,$6,NOW(),NULL,NULL)
RETURNING id, execution_state_id, agent_id, status, input, output, started_at, finished_at, deleted_at
`

type CreateAgentRunParams struct {
	ID               pgtype.UUID
	ExecutionStateID pgtype.UUID
	AgentID          pgtype.UUID
	Status           pgtype.Text
	Input            []byte
	Output           []byte
}

// =========================
// AGENT RUN
// =========================
func (q *Queries) CreateAgentRun(ctx context.Context, arg CreateAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, createAgentRun,
		arg.ID,
		arg.ExecutionStateID,
		arg.AgentID,
		arg.Status,
		arg.Input,
		arg.Output,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ExecutionStateID,
		&i.AgentID,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createApproval = `-- name: CreateApproval :one

INSERT INTO approval (
    id, execution_state_id, status, reviewer, comment, approved_at, deleted_at
)
VALUES ($1,$2,$3,$4,$5,$6,NULL)
RETURNING id, execution_state_id, status, reviewer, comment, approved_at, deleted_at
`

type CreateApprovalParams struct {
	ID               pgtype.UUID
	ExecutionStateID pgtype.UUID
	Status           pgtype.Text
	Reviewer         pgtype.Text
	Comment          pgtype.Text
	ApprovedAt       pgtype.Timestamptz
}

// =========================
// APPROVAL
// =========================
func (q *Queries) CreateApproval(ctx context.Context, arg CreateApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, createApproval,
		arg.ID,
		arg.ExecutionStateID,
		arg.Status,
		arg.Reviewer,
		arg.Comment,
		arg.ApprovedAt,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.ExecutionStateID,
		&i.Status,
		&i.Reviewer,
		&i.Comment,
		&i.ApprovedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createArtifact = `-- name: CreateArtifact :one

INSERT INTO artifact (
    id, project_id, type, name, latest_version, created_at, deleted_at
)
VALUES ($1,$2,$3,$4,$5,NOW(),NULL)
RETURNING id, project_id, type, name, latest_version, created_at, deleted_at
`

type CreateArtifactParams struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Type          pgtype.Text
	Name          pgtype.Text
	LatestVersion pgtype.Int4
}

// =========================
// ARTIFACT
// =========================
func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.ID,
		arg.ProjectID,
		arg.Type,
		arg.Name,
		arg.LatestVersion,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Name,
		&i.LatestVersion,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createArtifactVersion = `-- name: CreateArtifactVersion :one

INSERT INTO artifact_version (
    id, artifact_id, version, storage_uri, checksum, metadata, created_at, deleted_at
)
VALUES ($1,$2,$3,$4,$5,$6,NOW(),NULL)
RETURNING id, artifact_id, version, storage_uri, checksum, metadata, created_at, deleted_at
`

type CreateArtifactVersionParams struct {
	ID         pgtype.UUID
	ArtifactID pgtype.UUID
	Version    pgtype.Int4
	StorageUri pgtype.Text
	Checksum   pgtype.Text
	Metadata   []byte
}

// =========================
// ARTIFACT VERSION
// =========================
func (q *Queries) CreateArtifactVersion(ctx context.Context, arg CreateArtifactVersionParams) (ArtifactVersion, error) {
	row := q.db.QueryRow(ctx, createArtifactVersion,
		arg.ID,
		arg.ArtifactID,
		arg.Version,
		arg.StorageUri,
		arg.Checksum,
		arg.Metadata,
	)
	var i ArtifactVersion
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Version,
		&i.StorageUri,
		&i.Checksum,
		&i.Metadata,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createAuditLog = `-- name: CreateAuditLog :one

INSERT INTO audit_log (
    id, project_id, actor, action, payload, created_at, deleted_at
)
VALUES ($1,$2,$3,$4,$5,NOW(),NULL)
RETURNING id, project_id, actor, action, payload, created_at, deleted_at
`

type CreateAuditLogParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	Actor     pgtype.Text
	Action    pgtype.Text
	Payload   []byte
}

// =========================
// AUDIT LOG
// =========================
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ID,
		arg.ProjectID,
		arg.Actor,
		arg.Action,
		arg.Payload,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Actor,
		&i.Action,
		&i.Payload,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMemoryChunk = `-- name: CreateMemoryChunk :one

INSERT INTO memory_chunk (
    id, artifact_version_id, chunk_index, content, embedding, metadata, deleted_at
)
VALUES ($1,$2,$3,$4,$5,$6,NULL)
RETURNING id, artifact_version_id, chunk_index, content, embedding, metadata, deleted_at
`

type CreateMemoryChunkParams struct {
	ID                pgtype.UUID
	ArtifactVersionID pgtype.UUID
	ChunkIndex        pgtype.Int4
	Content           pgtype.Text
	Embedding         pgvector.Vector
	Metadata          []byte
}

// =========================
// MEMORY CHUNK
// =========================
func (q *Queries) CreateMemoryChunk(ctx context.Context, arg CreateMemoryChunkParams) (MemoryChunk, error) {
	row := q.db.QueryRow(ctx, createMemoryChunk,
		arg.ID,
		arg.ArtifactVersionID,
		arg.ChunkIndex,
		arg.Content,
		arg.Embedding,
		arg.Metadata,
	)
	var i MemoryChunk
	err := row.Scan(
		&i.ID,
		&i.ArtifactVersionID,
		&i.ChunkIndex,
		&i.Content,
		&i.Embedding,
		&i.Metadata,
		&i.DeletedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one

INSERT INTO project (
    id, name, description, workflow_id, workflow_version, status, created_at, updated_at, deleted_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, NOW(), NOW(), NULL
)
RETURNING id, name, description, workflow_id, workflow_version, status, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	ID              pgtype.UUID
	Name            string
	Description     pgtype.Text
	WorkflowID      pgtype.UUID
	WorkflowVersion pgtype.Int4
	Status          pgtype.Text
}

// =========================
// PROJECT
// =========================
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.WorkflowID,
		arg.WorkflowVersion,
		arg.Status,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.WorkflowID,
		&i.WorkflowVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createWorkflow = `-- name: CreateWorkflow :one

INSERT INTO workflow (
    id, name, version, start_state, active, created_at, deleted_at
)
VALUES (
    $1, $2, $3, $4, $5, NOW(), NULL
)
RETURNING id, name, version, start_state, active, created_at, deleted_at
`

type CreateWorkflowParams struct {
	ID         pgtype.UUID
	Name       string
	Version    pgtype.Int4
	StartState pgtype.Text
	Active     pgtype.Bool
}

// =========================
// WORKFLOW
// =========================
func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflow,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.StartState,
		arg.Active,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.StartState,
		&i.Active,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createWorkflowEvent = `-- name: CreateWorkflowEvent :one

INSERT INTO workflow_event (
    id, execution_id, event_name, payload, created_at, deleted_at
)
VALUES ($1,$2,$3,$4,NOW(),NULL)
RETURNING id, execution_id, event_name, payload, created_at, deleted_at
`

type CreateWorkflowEventParams struct {
	ID          pgtype.UUID
	ExecutionID pgtype.UUID
	EventName   pgtype.Text
	Payload     []byte
}

// =========================
// WORKFLOW EVENT
// =========================
func (q *Queries) CreateWorkflowEvent(ctx context.Context, arg CreateWorkflowEventParams) (WorkflowEvent, error) {
	row := q.db.QueryRow(ctx, createWorkflowEvent,
		arg.ID,
		arg.ExecutionID,
		arg.EventName,
		arg.Payload,
	)
	var i WorkflowEvent
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.EventName,
		&i.Payload,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createWorkflowExecution = `-- name: CreateWorkflowExecution :one

INSERT INTO workflow_execution (
    id, project_id, workflow_id, current_state, status,
    started_at, finished_at, deleted_at
)
VALUES ($1,$2,$3,$4,$5,NOW(),NULL,NULL)
RETURNING id, project_id, workflow_id, current_state, status, started_at, finished_at, deleted_at
`

type CreateWorkflowExecutionParams struct {
	ID           pgtype.UUID
	ProjectID    pgtype.UUID
	WorkflowID   pgtype.UUID
	CurrentState pgtype.Text
	Status       pgtype.Text
}

// =========================
// WORKFLOW EXECUTION
// =========================
func (q *Queries) CreateWorkflowExecution(ctx context.Context, arg CreateWorkflowExecutionParams) (WorkflowExecution, error) {
	row := q.db.QueryRow(ctx, createWorkflowExecution,
		arg.ID,
		arg.ProjectID,
		arg.WorkflowID,
		arg.CurrentState,
		arg.Status,
	)
	var i WorkflowExecution
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorkflowID,
		&i.CurrentState,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createWorkflowExecutionState = `-- name: CreateWorkflowExecutionState :one

INSERT INTO workflow_execution_state (
    id, execution_id, state_key, status, entered_at, exited_at, deleted_at
)
VALUES ($1,$2,$3,$4,NOW(),NULL,NULL)
RETURNING id, execution_id, state_key, status, entered_at, exited_at, deleted_at
`

type CreateWorkflowExecutionStateParams struct {
	ID          pgtype.UUID
	ExecutionID pgtype.UUID
	StateKey    pgtype.Text
	Status      pgtype.Text
}

// =========================
// WORKFLOW EXECUTION STATE
// =========================
func (q *Queries) CreateWorkflowExecutionState(ctx context.Context, arg CreateWorkflowExecutionStateParams) (WorkflowExecutionState, error) {
	row := q.db.QueryRow(ctx, createWorkflowExecutionState,
		arg.ID,
		arg.ExecutionID,
		arg.StateKey,
		arg.Status,
	)
	var i WorkflowExecutionState
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.StateKey,
		&i.Status,
		&i.EnteredAt,
		&i.ExitedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createWorkflowState = `-- name: CreateWorkflowState :one

INSERT INTO workflow_state (
    id, workflow_id, state_key, state_name, agent_name,
    timeout_seconds, retry_limit, is_terminal, deleted_at
)
VALUES (
    $1,$2,$3,$4,$5,$6,$7,$8,NULL
)
RETURNING id, workflow_id, state_key, state_name, agent_name, timeout_seconds, retry_limit, is_terminal, deleted_at
`

type CreateWorkflowStateParams struct {
	ID             pgtype.UUID
	WorkflowID     pgtype.UUID
	StateKey       pgtype.Text
	StateName      pgtype.Text
	AgentName      pgtype.Text
	TimeoutSeconds pgtype.Int4
	RetryLimit     pgtype.Int4
	IsTerminal     pgtype.Bool
}

// =========================
// WORKFLOW STATE
// =========================
func (q *Queries) CreateWorkflowState(ctx context.Context, arg CreateWorkflowStateParams) (WorkflowState, error) {
	row := q.db.QueryRow(ctx, createWorkflowState,
		arg.ID,
		arg.WorkflowID,
		arg.StateKey,
		arg.StateName,
		arg.AgentName,
		arg.TimeoutSeconds,
		arg.RetryLimit,
		arg.IsTerminal,
	)
	var i WorkflowState
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.StateKey,
		&i.StateName,
		&i.AgentName,
		&i.TimeoutSeconds,
		&i.RetryLimit,
		&i.IsTerminal,
		&i.DeletedAt,
	)
	return i, err
}

const createWorkflowStateInput = `-- name: CreateWorkflowStateInput :one

INSERT INTO workflow_state_input (
    id, workflow_state_id, artifact_type, required, deleted_at
)
VALUES ($1,$2,$3,$4,NULL)
RETURNING id, workflow_state_id, artifact_type, required, deleted_at
`

type CreateWorkflowStateInputParams struct {
	ID              pgtype.UUID
	WorkflowStateID pgtype.UUID
	ArtifactType    string
	Required        pgtype.Bool
}

// =========================
// WORKFLOW STATE INPUT
// =========================
func (q *Queries) CreateWorkflowStateInput(ctx context.Context, arg CreateWorkflowStateInputParams) (WorkflowStateInput, error) {
	row := q.db.QueryRow(ctx, createWorkflowStateInput,
		arg.ID,
		arg.WorkflowStateID,
		arg.ArtifactType,
		arg.Required,
	)
	var i WorkflowStateInput
	err := row.Scan(
		&i.ID,
		&i.WorkflowStateID,
		&i.ArtifactType,
		&i.Required,
		&i.DeletedAt,
	)
	return i, err
}

const createWorkflowStateOutput = `-- name: CreateWorkflowStateOutput :one

INSERT INTO workflow_state_output (
    id, workflow_state_id, artifact_type, deleted_at
)
VALUES ($1,$2,$3,NULL)
RETURNING id, workflow_state_id, artifact_type, deleted_at
`

type CreateWorkflowStateOutputParams struct {
	ID              pgtype.UUID
	WorkflowStateID pgtype.UUID
	ArtifactType    string
}

// =========================
// WORKFLOW STATE OUTPUT
// =========================
func (q *Queries) CreateWorkflowStateOutput(ctx context.Context, arg CreateWorkflowStateOutputParams) (WorkflowStateOutput, error) {
	row := q.db.QueryRow(ctx, createWorkflowStateOutput, arg.ID, arg.WorkflowStateID, arg.ArtifactType)
	var i WorkflowStateOutput
	err := row.Scan(
		&i.ID,
		&i.WorkflowStateID,
		&i.ArtifactType,
		&i.DeletedAt,
	)
	return i, err
}

const createWorkflowTransition = `-- name: CreateWorkflowTransition :one

INSERT INTO workflow_transition (
    id, workflow_id, from_state, event_name, condition, to_state, deleted_at
)
VALUES ($1,$2,$3,$4,$5,$6,NULL)
RETURNING id, workflow_id, from_state, event_name, condition, to_state, deleted_at
`

type CreateWorkflowTransitionParams struct {
	ID         pgtype.UUID
	WorkflowID pgtype.UUID
	FromState  pgtype.Text
	EventName  pgtype.Text
	Condition  pgtype.Text
	ToState    pgtype.Text
}

// =========================
// WORKFLOW TRANSITION
// =========================
func (q *Queries) CreateWorkflowTransition(ctx context.Context, arg CreateWorkflowTransitionParams) (WorkflowTransition, error) {
	row := q.db.QueryRow(ctx, createWorkflowTransition,
		arg.ID,
		arg.WorkflowID,
		arg.FromState,
		arg.EventName,
		arg.Condition,
		arg.ToState,
	)
	var i WorkflowTransition
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.FromState,
		&i.EventName,
		&i.Condition,
		&i.ToState,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
UPDATE agent
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const deleteAgentRun = `-- name: DeleteAgentRun :exec
UPDATE agent_run
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteAgentRun(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgentRun, id)
	return err
}

const deleteApproval = `-- name: DeleteApproval :exec
UPDATE approval
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteApproval(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteApproval, id)
	return err
}

const deleteArtifact = `-- name: DeleteArtifact :exec
UPDATE artifact
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteArtifact(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteArtifact, id)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
UPDATE project
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
UPDATE workflow
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteWorkflow(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkflow, id)
	return err
}

const deleteWorkflowExecution = `-- name: DeleteWorkflowExecution :exec
UPDATE workflow_execution
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteWorkflowExecution(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkflowExecution, id)
	return err
}

const deleteWorkflowExecutionState = `-- name: DeleteWorkflowExecutionState :exec
UPDATE workflow_execution_state
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteWorkflowExecutionState(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkflowExecutionState, id)
	return err
}

const deleteWorkflowState = `-- name: DeleteWorkflowState :exec
UPDATE workflow_state
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteWorkflowState(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkflowState, id)
	return err
}

const deleteWorkflowTransition = `-- name: DeleteWorkflowTransition :exec
UPDATE workflow_transition
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteWorkflowTransition(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkflowTransition, id)
	return err
}

const getAgentById = `-- name: GetAgentById :one
SELECT id, name, endpoint, type, active, deleted_at FROM agent
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAgentById(ctx context.Context, id pgtype.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentById, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Type,
		&i.Active,
		&i.DeletedAt,
	)
	return i, err
}

const getAgentRunById = `-- name: GetAgentRunById :one
SELECT id, execution_state_id, agent_id, status, input, output, started_at, finished_at, deleted_at FROM agent_run
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAgentRunById(ctx context.Context, id pgtype.UUID) (AgentRun, error) {
	row := q.db.QueryRow(ctx, getAgentRunById, id)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ExecutionStateID,
		&i.AgentID,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getApprovalById = `-- name: GetApprovalById :one
SELECT id, execution_state_id, status, reviewer, comment, approved_at, deleted_at FROM approval
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetApprovalById(ctx context.Context, id pgtype.UUID) (Approval, error) {
	row := q.db.QueryRow(ctx, getApprovalById, id)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.ExecutionStateID,
		&i.Status,
		&i.Reviewer,
		&i.Comment,
		&i.ApprovedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getArtifactById = `-- name: GetArtifactById :one
SELECT id, project_id, type, name, latest_version, created_at, deleted_at FROM artifact
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetArtifactById(ctx context.Context, id pgtype.UUID) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifactById, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Name,
		&i.LatestVersion,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectById = `-- name: GetProjectById :one
SELECT id, name, description, workflow_id, workflow_version, status, created_at, updated_at, deleted_at FROM project
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProjectById(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectById, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.WorkflowID,
		&i.WorkflowVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkflowById = `-- name: GetWorkflowById :one
SELECT id, name, version, start_state, active, created_at, deleted_at FROM workflow
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkflowById(ctx context.Context, id pgtype.UUID) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflowById, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.StartState,
		&i.Active,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkflowExecutionById = `-- name: GetWorkflowExecutionById :one
SELECT id, project_id, workflow_id, current_state, status, started_at, finished_at, deleted_at FROM workflow_execution
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkflowExecutionById(ctx context.Context, id pgtype.UUID) (WorkflowExecution, error) {
	row := q.db.QueryRow(ctx, getWorkflowExecutionById, id)
	var i WorkflowExecution
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorkflowID,
		&i.CurrentState,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkflowExecutionStateById = `-- name: GetWorkflowExecutionStateById :one
SELECT id, execution_id, state_key, status, entered_at, exited_at, deleted_at FROM workflow_execution_state
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkflowExecutionStateById(ctx context.Context, id pgtype.UUID) (WorkflowExecutionState, error) {
	row := q.db.QueryRow(ctx, getWorkflowExecutionStateById, id)
	var i WorkflowExecutionState
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.StateKey,
		&i.Status,
		&i.EnteredAt,
		&i.ExitedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkflowStateById = `-- name: GetWorkflowStateById :one
SELECT id, workflow_id, state_key, state_name, agent_name, timeout_seconds, retry_limit, is_terminal, deleted_at FROM workflow_state
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkflowStateById(ctx context.Context, id pgtype.UUID) (WorkflowState, error) {
	row := q.db.QueryRow(ctx, getWorkflowStateById, id)
	var i WorkflowState
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.StateKey,
		&i.StateName,
		&i.AgentName,
		&i.TimeoutSeconds,
		&i.RetryLimit,
		&i.IsTerminal,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkflowTransitionById = `-- name: GetWorkflowTransitionById :one
SELECT id, workflow_id, from_state, event_name, condition, to_state, deleted_at FROM workflow_transition
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkflowTransitionById(ctx context.Context, id pgtype.UUID) (WorkflowTransition, error) {
	row := q.db.QueryRow(ctx, getWorkflowTransitionById, id)
	var i WorkflowTransition
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.FromState,
		&i.EventName,
		&i.Condition,
		&i.ToState,
		&i.DeletedAt,
	)
	return i, err
}

const listAgentRuns = `-- name: ListAgentRuns :many
SELECT id, execution_state_id, agent_id, status, input, output, started_at, finished_at, deleted_at FROM agent_run
WHERE execution_state_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListAgentRuns(ctx context.Context, executionStateID pgtype.UUID) ([]AgentRun, error) {
	rows, err := q.db.Query(ctx, listAgentRuns, executionStateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentRun
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.ExecutionStateID,
			&i.AgentID,
			&i.Status,
			&i.Input,
			&i.Output,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, endpoint, type, active, deleted_at FROM agent
WHERE deleted_at IS NULL
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Endpoint,
			&i.Type,
			&i.Active,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactVersions = `-- name: ListArtifactVersions :many
SELECT id, artifact_id, version, storage_uri, checksum, metadata, created_at, deleted_at FROM artifact_version
WHERE artifact_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListArtifactVersions(ctx context.Context, artifactID pgtype.UUID) ([]ArtifactVersion, error) {
	rows, err := q.db.Query(ctx, listArtifactVersions, artifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtifactVersion
	for rows.Next() {
		var i ArtifactVersion
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.Version,
			&i.StorageUri,
			&i.Checksum,
			&i.Metadata,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT id, project_id, type, name, latest_version, created_at, deleted_at FROM artifact
WHERE project_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListArtifacts(ctx context.Context, projectID pgtype.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifacts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Name,
			&i.LatestVersion,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, project_id, actor, action, payload, created_at, deleted_at FROM audit_log
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAuditLogs(ctx context.Context, projectID pgtype.UUID) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Actor,
			&i.Action,
			&i.Payload,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryChunks = `-- name: ListMemoryChunks :many
SELECT id, artifact_version_id, chunk_index, content, embedding, metadata, deleted_at FROM memory_chunk
WHERE artifact_version_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListMemoryChunks(ctx context.Context, artifactVersionID pgtype.UUID) ([]MemoryChunk, error) {
	rows, err := q.db.Query(ctx, listMemoryChunks, artifactVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryChunk
	for rows.Next() {
		var i MemoryChunk
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactVersionID,
			&i.ChunkIndex,
			&i.Content,
			&i.Embedding,
			&i.Metadata,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, description, workflow_id, workflow_version, status, created_at, updated_at, deleted_at FROM project
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.WorkflowID,
			&i.WorkflowVersion,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowEvents = `-- name: ListWorkflowEvents :many
SELECT id, execution_id, event_name, payload, created_at, deleted_at FROM workflow_event
WHERE execution_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListWorkflowEvents(ctx context.Context, executionID pgtype.UUID) ([]WorkflowEvent, error) {
	rows, err := q.db.Query(ctx, listWorkflowEvents, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowEvent
	for rows.Next() {
		var i WorkflowEvent
		if err := rows.Scan(
			&i.ID,
			&i.ExecutionID,
			&i.EventName,
			&i.Payload,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowExecutionStates = `-- name: ListWorkflowExecutionStates :many
SELECT id, execution_id, state_key, status, entered_at, exited_at, deleted_at FROM workflow_execution_state
WHERE execution_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListWorkflowExecutionStates(ctx context.Context, executionID pgtype.UUID) ([]WorkflowExecutionState, error) {
	rows, err := q.db.Query(ctx, listWorkflowExecutionStates, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowExecutionState
	for rows.Next() {
		var i WorkflowExecutionState
		if err := rows.Scan(
			&i.ID,
			&i.ExecutionID,
			&i.StateKey,
			&i.Status,
			&i.EnteredAt,
			&i.ExitedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowExecutions = `-- name: ListWorkflowExecutions :many
SELECT id, project_id, workflow_id, current_state, status, started_at, finished_at, deleted_at FROM workflow_execution
WHERE project_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListWorkflowExecutions(ctx context.Context, projectID pgtype.UUID) ([]WorkflowExecution, error) {
	rows, err := q.db.Query(ctx, listWorkflowExecutions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowExecution
	for rows.Next() {
		var i WorkflowExecution
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.WorkflowID,
			&i.CurrentState,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowStateInputs = `-- name: ListWorkflowStateInputs :many
SELECT id, workflow_state_id, artifact_type, required, deleted_at FROM workflow_state_input
WHERE workflow_state_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListWorkflowStateInputs(ctx context.Context, workflowStateID pgtype.UUID) ([]WorkflowStateInput, error) {
	rows, err := q.db.Query(ctx, listWorkflowStateInputs, workflowStateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowStateInput
	for rows.Next() {
		var i WorkflowStateInput
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowStateID,
			&i.ArtifactType,
			&i.Required,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowStateOutputs = `-- name: ListWorkflowStateOutputs :many
SELECT id, workflow_state_id, artifact_type, deleted_at FROM workflow_state_output
WHERE workflow_state_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListWorkflowStateOutputs(ctx context.Context, workflowStateID pgtype.UUID) ([]WorkflowStateOutput, error) {
	rows, err := q.db.Query(ctx, listWorkflowStateOutputs, workflowStateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowStateOutput
	for rows.Next() {
		var i WorkflowStateOutput
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowStateID,
			&i.ArtifactType,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowStates = `-- name: ListWorkflowStates :many
SELECT id, workflow_id, state_key, state_name, agent_name, timeout_seconds, retry_limit, is_terminal, deleted_at FROM workflow_state
WHERE workflow_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListWorkflowStates(ctx context.Context, workflowID pgtype.UUID) ([]WorkflowState, error) {
	rows, err := q.db.Query(ctx, listWorkflowStates, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowState
	for rows.Next() {
		var i WorkflowState
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.StateKey,
			&i.StateName,
			&i.AgentName,
			&i.TimeoutSeconds,
			&i.RetryLimit,
			&i.IsTerminal,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowTransitions = `-- name: ListWorkflowTransitions :many
SELECT id, workflow_id, from_state, event_name, condition, to_state, deleted_at FROM workflow_transition
WHERE workflow_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListWorkflowTransitions(ctx context.Context, workflowID pgtype.UUID) ([]WorkflowTransition, error) {
	rows, err := q.db.Query(ctx, listWorkflowTransitions, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowTransition
	for rows.Next() {
		var i WorkflowTransition
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.FromState,
			&i.EventName,
			&i.Condition,
			&i.ToState,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, name, version, start_state, active, created_at, deleted_at FROM workflow
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListWorkflows(ctx context.Context) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.StartState,
			&i.Active,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agent
SET
    name = $2,
    endpoint = $3,
    type = $4,
    active = $5
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, endpoint, type, active, deleted_at
`

type UpdateAgentParams struct {
	ID       pgtype.UUID
	Name     pgtype.Text
	Endpoint pgtype.Text
	Type     pgtype.Text
	Active   pgtype.Bool
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.ID,
		arg.Name,
		arg.Endpoint,
		arg.Type,
		arg.Active,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Type,
		&i.Active,
		&i.DeletedAt,
	)
	return i, err
}

const updateAgentRun = `-- name: UpdateAgentRun :one
UPDATE agent_run
SET
    status = $2,
    output = $3,
    finished_at = $4
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, execution_state_id, agent_id, status, input, output, started_at, finished_at, deleted_at
`

type UpdateAgentRunParams struct {
	ID         pgtype.UUID
	Status     pgtype.Text
	Output     []byte
	FinishedAt pgtype.Timestamptz
}

func (q *Queries) UpdateAgentRun(ctx context.Context, arg UpdateAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, updateAgentRun,
		arg.ID,
		arg.Status,
		arg.Output,
		arg.FinishedAt,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ExecutionStateID,
		&i.AgentID,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateApproval = `-- name: UpdateApproval :one
UPDATE approval
SET
    status = $2,
    reviewer = $3,
    comment = $4,
    approved_at = $5
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, execution_state_id, status, reviewer, comment, approved_at, deleted_at
`

type UpdateApprovalParams struct {
	ID         pgtype.UUID
	Status     pgtype.Text
	Reviewer   pgtype.Text
	Comment    pgtype.Text
	ApprovedAt pgtype.Timestamptz
}

func (q *Queries) UpdateApproval(ctx context.Context, arg UpdateApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, updateApproval,
		arg.ID,
		arg.Status,
		arg.Reviewer,
		arg.Comment,
		arg.ApprovedAt,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.ExecutionStateID,
		&i.Status,
		&i.Reviewer,
		&i.Comment,
		&i.ApprovedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateArtifact = `-- name: UpdateArtifact :one
UPDATE artifact
SET
    type = $2,
    name = $3,
    latest_version = $4
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, type, name, latest_version, created_at, deleted_at
`

type UpdateArtifactParams struct {
	ID            pgtype.UUID
	Type          pgtype.Text
	Name          pgtype.Text
	LatestVersion pgtype.Int4
}

func (q *Queries) UpdateArtifact(ctx context.Context, arg UpdateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, updateArtifact,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.LatestVersion,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Name,
		&i.LatestVersion,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE project
SET
    name = $2,
    description = $3,
    workflow_id = $4,
    workflow_version = $5,
    status = $6,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, description, workflow_id, workflow_version, status, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	ID              pgtype.UUID
	Name            string
	Description     pgtype.Text
	WorkflowID      pgtype.UUID
	WorkflowVersion pgtype.Int4
	Status          pgtype.Text
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.WorkflowID,
		arg.WorkflowVersion,
		arg.Status,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.WorkflowID,
		&i.WorkflowVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateWorkflow = `-- name: UpdateWorkflow :one
UPDATE workflow
SET
    name = $2,
    version = $3,
    start_state = $4,
    active = $5
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, version, start_state, active, created_at, deleted_at
`

type UpdateWorkflowParams struct {
	ID         pgtype.UUID
	Name       string
	Version    pgtype.Int4
	StartState pgtype.Text
	Active     pgtype.Bool
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, updateWorkflow,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.StartState,
		arg.Active,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.StartState,
		&i.Active,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateWorkflowExecution = `-- name: UpdateWorkflowExecution :one
UPDATE workflow_execution
SET
    current_state = $2,
    status = $3,
    finished_at = $4
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, workflow_id, current_state, status, started_at, finished_at, deleted_at
`

type UpdateWorkflowExecutionParams struct {
	ID           pgtype.UUID
	CurrentState pgtype.Text
	Status       pgtype.Text
	FinishedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateWorkflowExecution(ctx context.Context, arg UpdateWorkflowExecutionParams) (WorkflowExecution, error) {
	row := q.db.QueryRow(ctx, updateWorkflowExecution,
		arg.ID,
		arg.CurrentState,
		arg.Status,
		arg.FinishedAt,
	)
	var i WorkflowExecution
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorkflowID,
		&i.CurrentState,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateWorkflowExecutionState = `-- name: UpdateWorkflowExecutionState :one
UPDATE workflow_execution_state
SET
    status = $2,
    exited_at = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, execution_id, state_key, status, entered_at, exited_at, deleted_at
`

type UpdateWorkflowExecutionStateParams struct {
	ID       pgtype.UUID
	Status   pgtype.Text
	ExitedAt pgtype.Timestamptz
}

func (q *Queries) UpdateWorkflowExecutionState(ctx context.Context, arg UpdateWorkflowExecutionStateParams) (WorkflowExecutionState, error) {
	row := q.db.QueryRow(ctx, updateWorkflowExecutionState, arg.ID, arg.Status, arg.ExitedAt)
	var i WorkflowExecutionState
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.StateKey,
		&i.Status,
		&i.EnteredAt,
		&i.ExitedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateWorkflowState = `-- name: UpdateWorkflowState :one
UPDATE workflow_state
SET
    state_key = $2,
    state_name = $3,
    agent_name = $4,
    timeout_seconds = $5,
    retry_limit = $6,
    is_terminal = $7
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_id, state_key, state_name, agent_name, timeout_seconds, retry_limit, is_terminal, deleted_at
`

type UpdateWorkflowStateParams struct {
	ID             pgtype.UUID
	StateKey       pgtype.Text
	StateName      pgtype.Text
	AgentName      pgtype.Text
	TimeoutSeconds pgtype.Int4
	RetryLimit     pgtype.Int4
	IsTerminal     pgtype.Bool
}

func (q *Queries) UpdateWorkflowState(ctx context.Context, arg UpdateWorkflowStateParams) (WorkflowState, error) {
	row := q.db.QueryRow(ctx, updateWorkflowState,
		arg.ID,
		arg.StateKey,
		arg.StateName,
		arg.AgentName,
		arg.TimeoutSeconds,
		arg.RetryLimit,
		arg.IsTerminal,
	)
	var i WorkflowState
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.StateKey,
		&i.StateName,
		&i.AgentName,
		&i.TimeoutSeconds,
		&i.RetryLimit,
		&i.IsTerminal,
		&i.DeletedAt,
	)
	return i, err
}

const updateWorkflowTransition = `-- name: UpdateWorkflowTransition :one
UPDATE workflow_transition
SET
    from_state = $2,
    event_name = $3,
    condition = $4,
    to_state = $5
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_id, from_state, event_name, condition, to_state, deleted_at
`

type UpdateWorkflowTransitionParams struct {
	ID        pgtype.UUID
	FromState pgtype.Text
	EventName pgtype.Text
	Condition pgtype.Text
	ToState   pgtype.Text
}

func (q *Queries) UpdateWorkflowTransition(ctx context.Context, arg UpdateWorkflowTransitionParams) (WorkflowTransition, error) {
	row := q.db.QueryRow(ctx, updateWorkflowTransition,
		arg.ID,
		arg.FromState,
		arg.EventName,
		arg.Condition,
		arg.ToState,
	)
	var i WorkflowTransition
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.FromState,
		&i.EventName,
		&i.Condition,
		&i.ToState,
		&i.DeletedAt,
	)
	return i, err
}
